import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const env = Object.fromEntries(fs.readFileSync('.env','utf8').split('\n').filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^["']|["']$/g,'')]}));
const sb = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_KEY);
const { data: ports } = await sb.from('portfolio').select('members');
const valid = new Set(ports.flatMap(p => (p.members||[]).map(m => String(m.id))));
const { data: hs } = await sb.from('holdings').select('*');
const orphan = hs.filter(h => !h.member_id || !valid.has(String(h.member_id)));
const ids = orphan.map(h => h.id);
const { data: txs } = await sb.from('transactions').select('*').in('holding_id', ids);
const ts = new Date().toISOString().replace(/[:.]/g,'-');
const backup = `orphan_holdings_backup_${ts}.json`;
fs.writeFileSync(backup, JSON.stringify({ holdings: orphan, transactions: txs||[] }, null, 2));
console.log('backup:', backup, '| holdings:', orphan.length, '| transactions:', (txs||[]).length);
const { error: te, count: tc } = await sb.from('transactions').delete({ count: 'exact' }).in('holding_id', ids);
if (te) console.error('tx delete error', te);
const { error: he, count: hc } = await sb.from('holdings').delete({ count: 'exact' }).in('id', ids);
if (he) { console.error('holding delete error', he); process.exit(1); }
console.log('deleted transactions:', tc, '| deleted holdings:', hc);
const { count } = await sb.from('holdings').select('*', { count: 'exact', head: true });
console.log('remaining holdings:', count);
